[server]
# Disable file watching to prevent path issues
fileWatcherType = "none"
runOnSave = false

# Enable development mode
enableCORS = false
enableXsrfProtection = false

[browser]
# Automatically open browser
gatherUsageStats = false

[theme]
# Use default theme
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
# Set logging level
level = "info"